manifest:
  version: 0.7

  defaults:
    remote: zephyrproject

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      repo-path: zephyr
      revision: a6eef0ba3755f2530c5ce93524e5ac4f5be30194 # v3.5.0
      path: zephyr
      import:
        path-prefix: deps
        name-allowlist:
          - cmsis
          - hal_stm32
          - mcuboot
          - mbedtls

  self:
    path: app