manifest:
  version: 0.7

  defaults:
    remote: zephyrproject

  remotes:
    - name: zephyrproject
      url-base: https://github.com/bayrem-gharsellaoui

  projects:
    - name: zephyr
      repo-path: zephyr
      revision: crypto_stm32_hash
      path: zephyr
      import:
        path-prefix: deps
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - mcuboot
          - mbedtls

  self:
    path: app